title: Marketing notes for programmer
description: A programmer's personal notes and reflections on marketing.
theme: just-the-docs
url: "https://marketingnotes.dev" # the base hostname & protocol for your site, e.g. http://example.com
favicon_ico: "/assets/images/favicon.png"
search_enabled: false
# External navigation links
nav_external_links:
  - title: View on GitHub
    url: https://github.com/slaily/marketingletter
callouts:
  note:
    title: Key takeaways
    color: yellow